server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: 19401940eY$
    url: jdbc:mysql://localhost/shopmedb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 182557182495-4ojqb7gpdf0cee6i97md5b3tns5sbc1e.apps.googleusercontent.com
            client-secret: zpJMafs7JAf4fNVLZirNcRnO
            scope:
            - email
            - profile
          facebook:
            client-id: 385247526176612
            client-secret: 690eed41082352ee7b0e1de7b72975d9
            scope:
            - email
            - public_profile